#Nom de l'application
spring.application.name=mini-scrum-backend
# L'API sera accessible sur http://localhost:8085
server.port=8086

# Adresse de la base de donnees PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Database_ScrumApp
# Nom d'utilisateur PostgreSQL
spring.datasource.username=${DB_USERNAME:postgres}
#password
spring.datasource.password=${DB_PASSWORD:root123}

spring.datasource.driver-class-name=org.postgresql.Driver

# "update" = Hibernate crée/modifie les tables automatiquement
# selon les classes @Entity — tu n'écris pas de SQL manuellement
spring.jpa.hibernate.ddl-auto=update
# Ne pas afficher les requêtes SQL dans la console (mettre true pour déboguer)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



app.frontend.url=http://localhost:4200,http://localhost:3000,http://localhost:3001,http://localhost:5173

# JWT
app.jwt.secret=${JWT_SECRET:c2NydW1hcHBzZWNyZXRrZXkxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=}
app.jwt.expiration=86400000
