#nom de l'application
spring.application.name=mini-scrum-backend
server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Database_ScrumApp
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
#controle la gestion automatique des table
spring.jpa.hibernate.ddl-auto=update
#affiche requete sql dans le console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS
app.frontend.url=http://localhost:4200,http://localhost:3000

# Logging
logging.level.com.miniscrum=DEBUG
logging.level.org.springframework.security=WARN
